/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as HostRouteImport } from './routes/host'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as HostMembersRouteImport } from './routes/host.members'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as HostEventsNewRouteImport } from './routes/host.events.new'
import { Route as HostEventsEventIdRouteImport } from './routes/host.events.$eventId'
import { Route as HostEventsEventIdIndexRouteImport } from './routes/host.events.$eventId.index'
import { Route as HostEventsEventIdEditRouteImport } from './routes/host.events.$eventId.edit'
import { Route as HostEventsEventIdCheckInRouteImport } from './routes/host.events.$eventId.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostMembersRoute = HostMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => HostRoute,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostEventsNewRoute = HostEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => HostRoute,
} as any)
const HostEventsEventIdRoute = HostEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => HostRoute,
} as any)
const HostEventsEventIdIndexRoute = HostEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostEventsEventIdRoute,
} as any)
const HostEventsEventIdEditRoute = HostEventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HostEventsEventIdRoute,
} as any)
const HostEventsEventIdCheckInRoute =
  HostEventsEventIdCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => HostEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/host': typeof HostRouteWithChildren
  '/tickets': typeof TicketsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/members': typeof HostMembersRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/': typeof HostIndexRoute
  '/host/events/$eventId': typeof HostEventsEventIdRouteWithChildren
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/check-in': typeof HostEventsEventIdCheckInRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
  '/host/events/$eventId/': typeof HostEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/tickets': typeof TicketsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/members': typeof HostMembersRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host': typeof HostIndexRoute
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/check-in': typeof HostEventsEventIdCheckInRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
  '/host/events/$eventId': typeof HostEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-host': typeof BecomeHostRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/host': typeof HostRouteWithChildren
  '/tickets': typeof TicketsRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/host/members': typeof HostMembersRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/': typeof HostIndexRoute
  '/host/events/$eventId': typeof HostEventsEventIdRouteWithChildren
  '/host/events/new': typeof HostEventsNewRoute
  '/host/events/$eventId/check-in': typeof HostEventsEventIdCheckInRoute
  '/host/events/$eventId/edit': typeof HostEventsEventIdEditRoute
  '/host/events/$eventId/': typeof HostEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-host'
    | '/events'
    | '/explore'
    | '/host'
    | '/tickets'
    | '/event/$eventId'
    | '/host/members'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/'
    | '/host/events/$eventId'
    | '/host/events/new'
    | '/host/events/$eventId/check-in'
    | '/host/events/$eventId/edit'
    | '/host/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-host'
    | '/events'
    | '/explore'
    | '/tickets'
    | '/event/$eventId'
    | '/host/members'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host'
    | '/host/events/new'
    | '/host/events/$eventId/check-in'
    | '/host/events/$eventId/edit'
    | '/host/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/become-host'
    | '/events'
    | '/explore'
    | '/host'
    | '/tickets'
    | '/event/$eventId'
    | '/host/members'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/'
    | '/host/events/$eventId'
    | '/host/events/new'
    | '/host/events/$eventId/check-in'
    | '/host/events/$eventId/edit'
    | '/host/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BecomeHostRoute: typeof BecomeHostRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  HostRoute: typeof HostRouteWithChildren
  TicketsRoute: typeof TicketsRoute
  EventEventIdRoute: typeof EventEventIdRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/members': {
      id: '/host/members'
      path: '/members'
      fullPath: '/host/members'
      preLoaderRoute: typeof HostMembersRouteImport
      parentRoute: typeof HostRoute
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/events/new': {
      id: '/host/events/new'
      path: '/events/new'
      fullPath: '/host/events/new'
      preLoaderRoute: typeof HostEventsNewRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/events/$eventId': {
      id: '/host/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/host/events/$eventId'
      preLoaderRoute: typeof HostEventsEventIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/events/$eventId/': {
      id: '/host/events/$eventId/'
      path: '/'
      fullPath: '/host/events/$eventId/'
      preLoaderRoute: typeof HostEventsEventIdIndexRouteImport
      parentRoute: typeof HostEventsEventIdRoute
    }
    '/host/events/$eventId/edit': {
      id: '/host/events/$eventId/edit'
      path: '/edit'
      fullPath: '/host/events/$eventId/edit'
      preLoaderRoute: typeof HostEventsEventIdEditRouteImport
      parentRoute: typeof HostEventsEventIdRoute
    }
    '/host/events/$eventId/check-in': {
      id: '/host/events/$eventId/check-in'
      path: '/check-in'
      fullPath: '/host/events/$eventId/check-in'
      preLoaderRoute: typeof HostEventsEventIdCheckInRouteImport
      parentRoute: typeof HostEventsEventIdRoute
    }
  }
}

interface HostEventsEventIdRouteChildren {
  HostEventsEventIdCheckInRoute: typeof HostEventsEventIdCheckInRoute
  HostEventsEventIdEditRoute: typeof HostEventsEventIdEditRoute
  HostEventsEventIdIndexRoute: typeof HostEventsEventIdIndexRoute
}

const HostEventsEventIdRouteChildren: HostEventsEventIdRouteChildren = {
  HostEventsEventIdCheckInRoute: HostEventsEventIdCheckInRoute,
  HostEventsEventIdEditRoute: HostEventsEventIdEditRoute,
  HostEventsEventIdIndexRoute: HostEventsEventIdIndexRoute,
}

const HostEventsEventIdRouteWithChildren =
  HostEventsEventIdRoute._addFileChildren(HostEventsEventIdRouteChildren)

interface HostRouteChildren {
  HostMembersRoute: typeof HostMembersRoute
  HostIndexRoute: typeof HostIndexRoute
  HostEventsEventIdRoute: typeof HostEventsEventIdRouteWithChildren
  HostEventsNewRoute: typeof HostEventsNewRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostMembersRoute: HostMembersRoute,
  HostIndexRoute: HostIndexRoute,
  HostEventsEventIdRoute: HostEventsEventIdRouteWithChildren,
  HostEventsNewRoute: HostEventsNewRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BecomeHostRoute: BecomeHostRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  HostRoute: HostRouteWithChildren,
  TicketsRoute: TicketsRoute,
  EventEventIdRoute: EventEventIdRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
